
#pragma once

#include "VideoWnd.h"

class CBitItem;
class CHaoYiView;

// 注意：这里的视频窗口是按照降序排列...
typedef	map<int, CVideoWnd*, greater<int>>	GM_MapVideo;

class CMidView : public CWnd
{
public:
	CMidView(CHaoYiView * lpParent);
	virtual ~CMidView();
protected:
	afx_msg int OnCreate(LPCREATESTRUCT lpCreateStruct);
	afx_msg void OnSize(UINT nType, int cx, int cy);
	afx_msg BOOL OnEraseBkgnd(CDC* pDC);
	DECLARE_MESSAGE_MAP()
public:
	int				GetVideoTotalNum() { return m_MapVideo.size(); }
	int				GetVideoCurPage() { return m_nCurPage; }
	int				GetVideoMaxPage() { return m_nMaxPage; }
	CFont    *		GetVideoFont() { return &m_VideoFont; }
	BOOL			IsFullScreen() { return m_bIsFullScreen; }
public:
	void			OnPagePrev();						// 点击上一页...
	void			OnPageJump();						// 点击跳转页...
	void			OnPageNext();						// 点击下一页...
	void			ReleaseFocus();						// 释放焦点...
	void			BuildVideoByWeb();					// 通过网站配置创建窗口...
	void			doDelDVR(int nCameraID);			// 删除指定摄像头...
	void			doLeftFocus(int nCameraID);			// 左侧点击...
	void			doMoveWindow(CRect & rcArea);		// 移动窗口...
	void			LayoutVideoWnd(int cx, int cy);		// 排列窗口...
	int				GetNextAutoID(int nCurDBCameraID);	// 得到下一个窗口编号...
	BOOL			ChangeFullScreen(BOOL bFullScreen);	// 设置全屏模式...
	CCamera     *	FindDBCameraByID(int nDBCameraID);
	CCamera		*	FindDBCameraBySN(string & inDeviceSN);
	CCamera		*	BuildWebCamera(GM_MapData & inWebData);
	GM_Error		AddNewCamera(GM_MapData & inNetData, CAMERA_TYPE inType, int & outDBCameraID);
	GM_Error		doCameraUDPData(GM_MapData & inNetData, CAMERA_TYPE inType, int & outDBCameraID);
	BOOL			doWebStatCamera(int nDBCamera, int nStatus, int nErrCode, LPCTSTR lpszErrMsg);
	BOOL			Create(UINT wStyle, const CRect & rect, CWnd * pParentWnd);
	void			OnWebAuthResult(int nType, BOOL bAuthOK);
	string			GetDefaultCameraName();				// 获取默认通道名称...
	void			doChangePageSize();					// 响应分页变化事件...
private:
	void			FixVideoWnd();						// 锁定窗口...
	void			BuildResource();					// 创建资源...
	void			DestroyResource();					// 销毁资源...
	void			DrawNotice(CDC * pDC);				// 打印警告...
	void			DrawBackLine(CDC * pDC);			// 绘制线框...
private:
	CRect			m_rcOrigin;							// 原始矩形区
	BOOL			m_bIsFullScreen;					// 全屏标志
	CString			m_strNotice;						// 提示信息

	CBitItem	 *	m_BitArray[CVideoWnd::kBitNum];		// 按钮列表...
	CHaoYiView	 *	m_lpParentDlg;						// 父窗口对象...
	CFont			m_VideoFont;						// 字体对象...

	int				m_nCurPage;							// 当前页...
	int				m_nMaxPage;							// 总页数...
	int				m_nFirstID;							// 第一个窗口的编号...
	GM_MapVideo		m_MapVideo;							// 视频窗口集合 => DBCameraID => CVideoWnd
};
