
#pragma once

#include "SortListCtrl.h"
#include "VideoWnd.h"
#include "QRStatic.h"

class CBitItem;
class CRightView;
class CPaneContent : public CDialog
{
	DECLARE_DYNAMIC(CPaneContent)
public:
	CPaneContent(CWnd* pParent = NULL);
	virtual ~CPaneContent();
	enum { IDD = IDD_PANECONTENT };
protected:
	virtual BOOL OnInitDialog();
	virtual void DoDataExchange(CDataExchange* pDX);
	afx_msg void OnSize(UINT nType, int cx, int cy);
	afx_msg void OnLButtonUp(UINT nFlags, CPoint point);
	afx_msg void OnLButtonDown(UINT nFlags, CPoint point);
	afx_msg void OnMouseMove(UINT nFlags, CPoint point);
	afx_msg BOOL OnEraseBkgnd(CDC* pDC);
	DECLARE_MESSAGE_MAP()
public:
	enum {
		kSplitterHeight = 3,
	};
public:
	HBRUSH			GetVideoBack()		{ return m_hVideoBack; }
	HCURSOR			GetHandCursor()		{ return m_hHandCur; }
	CBitItem	**	GetBitArray()		{ return m_BitArray; }
	CFont		 *	GetVideoFont()		{ return &m_VideoFont; }
private:
	HCURSOR			GetSysHandCursor();					// 得到系统鼠标...
	void			DrawSplitBar(LPRECT lpRect);		// 绘制分隔符...

	void			OnMidSplitEnd(int nOffset);			// 拖拽分隔符停止...
	BOOL			IsMidCanSplit(CPoint & point);		// 是否还能拖动...

	void			BuildListCtrl();					// 创建列表对象...
	void			BuildResource();					// 创建资源...
	void			DestroyResource();					// 销毁资源...
private:
	CPrevStatic		m_PrevWnd;							// 预览窗口栏...
	CSortListCtrl	m_ListCtrl;							// 列表信息栏...
	BOOL			m_bMidDraging;						// Flag for Middle Split-Bar...
	CRect			m_rcSplitMidNew;					// 分隔符的新矩形区...
	CRect			m_rcSplitMidSrc;					// 分隔符的原矩形区...

	HCURSOR			m_hCurVerSplit;						// 分隔符需要的垂直鼠标...
	CImageList		m_ListImage;						// 列表对象需要的图片列表...

	CFont			m_VideoFont;						// The font object for Video-Window...
	HCURSOR			m_hHandCur;							// Store the hand cursor...
	HBRUSH			m_hVideoBack;						// 视频窗口背景刷子...

	CRightView	*	m_lpRightView;						// 视频窗口管理器...
	CBitItem	*	m_BitArray[CVideoWnd::kBitNum];		// 按钮列表...
};
