
#pragma once

#include "OSThread.h"

class CHaoYiView;
class CWebThread : public OSThread
{
public:
	CWebThread(CHaoYiView * lpView);
	~CWebThread();
public:
	GM_Error	Initialize();							// 初始化线程...
	int			GetWebType() { return m_nWebType; }		// 获取网站类型...
	void		doPostCurl(char *pData, size_t nSize);	// 处理汇报反馈...
	BOOL		doWebRegCamera(GM_MapData & inData);	// 向网站注册摄像头...
	BOOL		doWebDelCamera(string & inDeviceSN);	// 向网站删除摄像头...
	BOOL		doWebStatCamera(int nDBCamera, int nStatus);
	BOOL		doWebGatherLogout();		// 采集端退出汇报...
private:
	virtual void	Entry();				// 线程函数...
	BOOL			RegisterHaoYi();		// 验证许可证...
	BOOL			RegisterGather();		// 注册采集端...
	BOOL			RegisterCamera();		// 注册摄像头...
private:
	enum {
		kRegGather	  = 0,					// 正在注册采集端...
		kRegHaoYi	  = 1,					// 正在验证许可证...
		kRegCamera	  = 2,					// 正在注册摄像头...
		kDelCamera    = 3,					// 正在删除摄像头...
		kStatCamera	  = 4,					// 正在汇报通道状态...
		kGatherLogout = 5,					// 采集端退出汇报...
	}m_eRegState;
private:
	GM_MapCourse	m_dbMapCourse;			// 摄像头下的录像课表...
	string			m_strRemoteAddr;		// Transmit服务器地址...
	int				m_nRemotePort;			// Transmit服务器端口...
	string			m_strTrackerAddr;		// Tracker服务器地址...
	int				m_nTrackerPort;			// Tracker服务器端口...
	int				m_HaoYiGatherID;		// 在中心服务器上的采集端编号...
	string			m_strWebName;			// 节点服务器名称...
	string			m_strWebTag;			// 节点服务器唯一标识...
	int				m_nWebType;				// 节点服务器类型标识...
	int				m_nDBGatherID;			// 数据库中采集端编号...
	int				m_nDBCameraID;			// 数据库中摄像头编号...
	string			m_strDBCameraName;		// 数据库中摄像头名称...
	int				m_nCurCameraCount;		// 已经注册的摄像头个数...
	CHaoYiView	*	m_lpHaoYiView;			// 视图指针...
};
